export const ERROR = Object.freeze({
    ERROR: {
        WITHOUT_ERROR: 0,
        WITH_ERROR: 1
    },
    ERROR_CODE: {
        SUCCESS: 200,
        NO_DATA_FOUND: 404,
        INTERNAL_SERVER_ERROR: 500,
        EMAIL_EXIST: 1007,
        MOBILE_EXIST: 1004,
        PARAMETER_MISSING: 1001,
        INCORRECT_PASSWORD: 1006,
        INCORRECT_OTP: 1008,
        CURRENT_PASSWORD_NOT_MATCHED : 1009,
        MOBILE_NOT_REGISTERED : 1005,


        UNAUTHORIZED_USER: 401,
        EMAIL_NOT_EXIST: 101,
        USER_NOT_EXIST: 103,
        EMAIL_PHONE_EXIST: 106,
        LINK_EXPIRE: 110,
        LINK_ALREADY_USED: 111,
        DEACTIVATED_USER: 107,
        DUPLICATE_DEPT: 108,
        CLIENT_MAP_WITH_DEPT: 109,
        DUPLICATE_DOCUMENT: 112,
        DUPLICATE_ROLE_NAME: 115,
        DUPLICATE_FEEDBACK: 117,
        DUPLICATE_INDUSTRY__TYPE: 119,
    }
});